version: "3"

networks:
  waasq_telegram_bot_network:

services:
  mongo:
    image: mongo:7-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ACCOUNT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "mongo"
    volumes:
      - ./db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "express"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ACCOUNT}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ACCOUNT}:${MONGO_PASSWORD}@mongo:27017/


  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto:/mosquitto
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "mqtt"
    ports:
      - 1883:1883
  python:
    build:
      context: .
      dockerfile: ./Dockerfile.waasq
    restart: always
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "python"
    volumes:
      - .:/src/app
    tty: true
    command: sh
  node:
    build:
      context: .
      dockerfile: ./Dockerfile.bot
    restart: always
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "node"
    volumes:
      - .:/src/app
    tty: true
    command: sh
    env_file:
      - .env