FROM 192.168.76.30:5000/python:arm64
WORKDIR /src/app

COPY requirements.txt .
COPY waasq.py .
COPY mqtt.py .
COPY machine_reader.py .
COPY devices.json .


RUN pip install -r requirements.txt

CMD ["python", "mqtt.py"]