version: "3"

networks:
  waasq_telegram_bot_network:

services:
  mqtt:
    image: 192.168.76.30:5000/eclipse-mosquitto:arm64
    volumes:
      - ./mosquitto:/mosquitto
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "mqtt"
    ports:
      - 1883:1883
  python:
    build:
      context: deploy
      dockerfile: Dockerfile.pi.waasq
    restart: always
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "python"
    env_file:
      - .env
  node:
    build:
      context: deploy
      dockerfile: Dockerfile.pi.bot
    restart: always
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "node"
    env_file:
      - .env
  api:
    build:
      context: deploy
      dockerfile: Dockerfile.pi.api
    restart: always
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "api"
    env_file:
      - .env
    ports:
      - 30080:3000
