FROM node:18-alpine

RUN apk add curl git 

WORKDIR /src/app

COPY package-lock.json .
COPY package.json .
COPY bot.js .
COPY machine-reader.js .
COPY devices.json .

RUN npm install

CMD ["node", "bot.js"]