version: "3"

networks:
  waasq_telegram_bot_network:

services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto:/mosquitto
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "mqtt"
    ports:
      - 1883:1883
  python:
    build:
      context: .
      dockerfile: ./Dockerfile.waasq
    restart: always
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "python"
    volumes:
      - .:/src/app
    tty: true
    command: sh
  node:
    build:
      context: .
      dockerfile: ./Dockerfile.bot
    restart: always
    networks:
      waasq_telegram_bot_network:
        aliases:
          - "node"
    volumes:
      - .:/src/app
    tty: true
    command: sh
    env_file:
      - .env